apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "platform.fullname" . }}
  labels:
    {{- include "platform.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "platform.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "platform.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PORT
              value: "80"
            - name: ENVIRONMENT
              value: "development"
            - name: MONGO_USER
              value: "root"
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "mongo-mongodb"
                  key: "mongodb-root-password"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: "platform-jwt-secret"
                  key: "jwt"
            - name: MONGO_HOST
              value: "mongo-mongodb-headless"
            - name: MONGO_PORT
              value: "27017"
            - name: DATABASE
              value: "fluidtrends"
            - name: ENDPOINT_STORAGE
              value: {{ .Values.image.endpointStorage | quote }}
            - name: STORAGE_TLS
              value: {{ .Values.image.minioEnableTls | quote }}
            - name: ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: "gitlab-minio-secret"
                  key: "accesskey"
            - name: SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: "gitlab-minio-secret"
                  key: "secretkey"
            - name: ETH_GATEWAY
              value: {{ .Values.image.ethGateway | quote }}
            - name: ETH_GATEWAY_KEY
              value: {{ .Values.image.ethGatewayKey | quote }}
            - name: ETH_CONTRACT_ADDRESS
              value: {{ .Values.image.ethContractAddress | quote }}
            - name: ETH_MINT_TOPIC
              value: {{ .Values.image.ethMintTopic | quote }}
            - name: ETH_STATE_TOPIC
              value: {{ .Values.image.ethStateTopic | quote }}
            - name: ETH_STATE_EVENT
              value: {{ .Values.image.ethStateEvent | quote }}
            - name: ETH_MINT_EVENT
              value: {{ .Values.image.ethMintEvent | quote }}
            - name: CITY_DOMAIN
              value: {{ .Values.image.cityDomain | quote }}
            - name: NFT_BUCKET
              value: {{ .Values.image.nftBucket | quote }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
