apiVersion: v1
kind: Secret
metadata:
  name: "platform-jwt-secret"
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  # retrieve the secret data using lookup function and when not exists, return an empty dictionary / map as result
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "platform-jwt-secret") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  # set $platformJwtSecret to existing secret data or generate a random one when not exists
  {{- $platformJwtSecret := (get $secretData "platform-jwt-secret") | default (randAlphaNum 32 | b64enc) }}
  jwt: {{ $platformJwtSecret | quote }}
